-- Datos de prueba para la aplicación
INSERT INTO usuarios (nombre, email, password, rol) VALUES ('Juan Pérez', 'juan@email.com', '123456', 'USER');
INSERT INTO usuarios (nombre, email, password, rol) VALUES ('María García', 'maria@email.com', 'password', 'USER');
INSERT INTO usuarios (nombre, email, password, rol) VALUES ('Admin Sistema', 'admin@email.com', 'admin123', 'ADMIN');
INSERT INTO usuarios (nombre, email, password, rol) VALUES ('ejemplo', 'ejemplo@ejemplo.cl', 'ejemplo', 'USER');

-- Datos de prueba para tutoriales de desarrollo de videojuegos
INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Introducción a Unity 3D', 'https://logos-world.net/wp-content/uploads/2023/01/Unity-Logo.png', 'Unity es uno de los motores de juegos más populares del mundo.\n\nPrimeros pasos:\n1. Descargar Unity Hub\n2. Instalar una versión LTS\n3. Crear nuevo proyecto 3D\n4. Familiarizarse con la interfaz\n\nComponentes básicos:\n- Scene: escena del juego\n- Hierarchy: jerarquía de objetos\n- Inspector: propiedades\n- Project: archivos del proyecto\n\nScript básico:\nusing UnityEngine;\n\npublic class PlayerController : MonoBehaviour {\n    void Update() {\n        transform.Translate(Input.GetAxis("Horizontal") * Time.deltaTime, 0, 0);\n    }\n}', 'Aprende Unity desde cero para crear videojuegos', 1);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Programación en C# para Juegos', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png', 'C# es el lenguaje principal para programar en Unity.\n\nConceptos fundamentales:\n- Variables y tipos de datos\n- Funciones y métodos\n- Clases y objetos\n- Herencia y polimorfismo\n\nEjemplo de clase Player:\npublic class Player : MonoBehaviour {\n    public float speed = 5f;\n    public int health = 100;\n    \n    void Start() {\n        Debug.Log("Jugador iniciado");\n    }\n    \n    void Update() {\n        Move();\n    }\n    \n    void Move() {\n        float horizontal = Input.GetAxis("Horizontal");\n        float vertical = Input.GetAxis("Vertical");\n        \n        Vector3 direction = new Vector3(horizontal, 0, vertical);\n        transform.Translate(direction * speed * Time.deltaTime);\n    }\n}', 'Domina C# para programar mecánicas de juego', 2);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Diseño de Niveles en Unity', 'https://picsum.photos/200/300', 'El diseño de niveles es crucial para la experiencia del jugador.\n\nPrincipios básicos:\n1. Flujo del jugador\n2. Dificultad progresiva\n3. Puntos de interés\n4. Navegación clara\n\nHerramientas en Unity:\n- ProBuilder: modelado básico\n- Terrain: terrenos\n- Prefabs: objetos reutilizables\n- Lighting: iluminación\n\nTips importantes:\n- Usa greyboxing primero\n- Testea constantemente\n- Considera la cámara\n- Optimiza el rendimiento', 'Crea niveles atractivos y funcionales', 3);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Pixel Art para Videojuegos', 'https://i.imgur.com/8BitArt.png', 'El pixel art es un estilo artístico popular en juegos indie.\n\nHerramientas recomendadas:\n- Aseprite (pago)\n- GIMP (gratis)\n- Piskel (online)\n- GraphicsGale\n\nTécnicas básicas:\n1. Paleta de colores limitada\n2. Aliasing controlado\n3. Dithering para gradientes\n4. Animación frame por frame\n\nTips para principiantes:\n- Empieza con resoluciones bajas (16x16, 32x32)\n- Usa referencias\n- Practica formas básicas\n- Estudia juegos clásicos\n\nAnimación básica:\n- Caminar: 4-6 frames\n- Saltar: 3-4 frames\n- Idle: 2-4 frames sutiles', 'Crea arte pixel perfecto para tus juegos', 1);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Audio en Videojuegos con FMOD', 'https://picsum.photos/200/301 ', 'FMOD es una potente herramienta para audio interactivo en juegos.\n\nConceptos clave:\n- Events: sonidos activables\n- Parameters: variables de control\n- Snapshots: estados de audio\n- Banks: archivos de audio\n\nIntegración con Unity:\n1. Importar FMOD Unity Integration\n2. Configurar settings\n3. Crear eventos en FMOD Studio\n4. Reproducir desde código\n\nEjemplo de código:\nusing FMODUnity;\n\npublic class AudioManager : MonoBehaviour {\n    [EventRef]\n    public string footstepEvent;\n    \n    void PlayFootstep() {\n        RuntimeManager.PlayOneShot(footstepEvent, transform.position);\n    }\n}', 'Implementa audio profesional en tus juegos', 2);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Godot Engine para Principiantes', 'https://godotengine.org/assets/press/logo_vertical_color_dark.png', 'Godot es un motor de juegos gratuito y open source.\n\nVentajas de Godot:\n- Completamente gratis\n- Ligero y rápido\n- Soporte 2D y 3D\n- Lenguaje GDScript fácil\n- Nodos y escenas\n\nEstructura básica:\n- Nodos: elementos del juego\n- Escenas: colección de nodos\n- Scripts: lógica del juego\n\nScript básico en GDScript:\nextends KinematicBody2D\n\nvar speed = 200\n\nfunc _ready():\n    print("Jugador listo")\n\nfunc _physics_process(delta):\n    var velocity = Vector2()\n    \n    if Input.is_action_pressed("ui_right"):\n        velocity.x += speed\n    if Input.is_action_pressed("ui_left"):\n        velocity.x -= speed\n    \n    move_and_slide(velocity)', 'Descubre Godot como alternativa gratuita', 3);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Shaders Básicos en Unity', 'https://picsum.photos/200/302', 'Los shaders controlan cómo se renderizan los materiales.\n\nTipos de shaders:\n- Surface Shader: más fácil\n- Vertex/Fragment: más control\n- Compute Shader: cálculos GPU\n\nShader básico (Surface):\nShader "Custom/BasicColor" {\n    Properties {\n        _MainTex ("Texture", 2D) = "white" {}\n        _Color ("Color", Color) = (1,1,1,1)\n    }\n    SubShader {\n        Tags { "RenderType"="Opaque" }\n        CGPROGRAM\n        #pragma surface surf Lambert\n        \n        sampler2D _MainTex;\n        fixed4 _Color;\n        \n        struct Input {\n            float2 uv_MainTex;\n        };\n        \n        void surf (Input IN, inout SurfaceOutput o) {\n            fixed4 c = tex2D(_MainTex, IN.uv_MainTex) * _Color;\n            o.Albedo = c.rgb;\n        }\n        ENDCG\n    }\n}', 'Crea efectos visuales personalizados', 1);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Game Design Document (GDD)', 'https://picsum.photos/200/303', 'El GDD es la biblia de tu videojuego durante el desarrollo.\n\nSecciones principales:\n1. Concepto del juego\n2. Mecánicas principales\n3. Historia y personajes\n4. Arte y audio\n5. Interfaz de usuario\n6. Monetización\n7. Plataformas objetivo\n\nEstructura recomendada:\n- Resumen ejecutivo (1 página)\n- Gameplay core loop\n- Progresión del jugador\n- Sistemas de juego\n- Especificaciones técnicas\n\nTips importantes:\n- Mantén el documento vivo\n- Sé específico pero flexible\n- Incluye mockups y diagramas\n- Revisa regularmente con el equipo\n- Versiona los cambios', 'Planifica tu juego antes de programar', 2);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Optimización de Juegos Móviles', 'https://developer.android.com/images/brand/Android_Robot.png', 'Los juegos móviles requieren optimización especial.\n\nÁreas clave de optimización:\n1. Rendimiento de CPU\n2. Uso de memoria\n3. Batería\n4. Almacenamiento\n\nTécnicas en Unity:\n- Object Pooling para proyectiles\n- LOD (Level of Detail) para modelos\n- Texture Compression\n- Batching de draw calls\n- Culling de objetos\n\nEjemplo Object Pool:\npublic class BulletPool : MonoBehaviour {\n    public GameObject bulletPrefab;\n    public int poolSize = 20;\n    private Queue<GameObject> bulletPool;\n    \n    void Start() {\n        bulletPool = new Queue<GameObject>();\n        for(int i = 0; i < poolSize; i++) {\n            GameObject bullet = Instantiate(bulletPrefab);\n            bullet.SetActive(false);\n            bulletPool.Enqueue(bullet);\n        }\n    }\n}', 'Haz que tu juego funcione bien en móviles', 3);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Inteligencia Artificial para NPCs', 'https://i.imgur.com/AIGameDev.png', 'Crea NPCs inteligentes que mejoren la experiencia de juego.\n\nTipos de IA en juegos:\n1. Finite State Machines (FSM)\n2. Behavior Trees\n3. Pathfinding (A*)\n4. Flocking (bandadas)\n\nEjemplo FSM básico:\npublic enum EnemyState {\n    Patrol,\n    Chase,\n    Attack,\n    Dead\n}\n\npublic class EnemyAI : MonoBehaviour {\n    public EnemyState currentState;\n    public Transform player;\n    public float detectionRange = 5f;\n    \n    void Update() {\n        switch(currentState) {\n            case EnemyState.Patrol:\n                PatrolBehavior();\n                break;\n            case EnemyState.Chase:\n                ChaseBehavior();\n                break;\n        }\n    }\n    \n    void PatrolBehavior() {\n        float distanceToPlayer = Vector3.Distance(transform.position, player.position);\n        if(distanceToPlayer < detectionRange) {\n            currentState = EnemyState.Chase;\n        }\n    }\n}', 'Programa enemigos y aliados inteligentes', 1);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Animación 2D en Unity', 'https://docs.unity3d.com/uploads/Main/MecanimAnimationClipExample.png', 'La animación 2D da vida a tus personajes y objetos.\n\nHerramientas principales:\n- Animator Controller: máquina de estados\n- Animation Window: crear clips\n- Sprite Renderer: mostrar sprites\n- 2D Animation Package: rigging avanzado\n\nPasos básicos:\n1. Importar sprite sheet\n2. Cortar sprites individuales\n3. Crear Animation Clip\n4. Configurar Animator Controller\n5. Añadir transiciones', 'Anima personajes 2D de forma profesional', 2);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Sistema de Partículas en Unity', 'https://docs.unity3d.com/uploads/Main/ParticleSystemCurveEditor.png', 'Los sistemas de partículas crean efectos visuales impactantes.\n\nEfectos comunes:\n- Fuego y humo\n- Explosiones\n- Magia y hechizos\n- Lluvia y nieve\n- Sangre y chispas\n\nMódulos importantes:\n- Emission: cuántas partículas\n- Shape: forma de emisión\n- Velocity: velocidad inicial\n- Color over Lifetime: cambio de color\n- Size over Lifetime: cambio de tamaño', 'Crea efectos visuales espectaculares', 3);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Blender para Game Assets', 'https://download.blender.org/branding/community/blender_community_badge_white.svg', 'Blender es una herramienta gratuita para crear modelos 3D.\n\nFlujo de trabajo básico:\n1. Modelado: crear la forma\n2. UV Mapping: desenvolver el modelo\n3. Texturizado: aplicar materiales\n4. Rigging: esqueleto para animación\n5. Animación: movimiento\n6. Exportación: formato para Unity\n\nTips para game assets:\n- Mantén low poly count\n- Usa texturas de potencias de 2\n- Optimiza UV maps\n- Exporta en FBX para Unity', 'Modela assets 3D profesionales gratis', 1);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Networking Multijugador con Mirror', 'https://mirror-networking.com/docs/Images/MirrorIcon.png', 'Mirror es una solución de networking para Unity.\n\nConceptos clave:\n- Server: autoridad del juego\n- Client: jugadores conectados\n- NetworkBehaviour: scripts de red\n- NetworkIdentity: objetos de red\n- Commands: cliente a servidor\n- ClientRpc: servidor a clientes\n\nEjemplo básico de movimiento en red con sincronización automática entre jugadores.', 'Crea juegos multijugador en línea', 2);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Procedural Generation', 'https://i.imgur.com/ProceduralGen.png', 'La generación procedural crea contenido automáticamente.\n\nTipos de generación:\n- Terrenos: mapas infinitos\n- Dungeons: mazmorras aleatorias\n- Ciudades: edificios y calles\n- Texturas: patrones únicos\n\nAlgoritmos comunes:\n- Perlin Noise: terrenos naturales\n- Cellular Automata: cuevas\n- Wave Function Collapse: patrones\n- L-Systems: plantas y fractales', 'Genera mundos infinitos automáticamente', 3);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('UI/UX para Videojuegos', 'https://unity.com/sites/default/files/styles/16_9_s_scale_width_1920/public/2020-05/Unity-UI-design-header.jpg', 'Una buena interfaz mejora la experiencia del jugador.\n\nPrincipios de UI en juegos:\n1. Claridad: información fácil de leer\n2. Consistencia: estilo unificado\n3. Feedback: respuesta a acciones\n4. Accesibilidad: para todos los jugadores\n\nElementos comunes:\n- HUD: vida, mana, minimapa\n- Menús: opciones, inventario\n- Diálogos: conversaciones\n- Notificaciones: logros, mensajes', 'Diseña interfaces intuitivas y atractivas', 1);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Monetización en Juegos Móviles', 'https://developers.google.com/admob/images/admob_logo.png', 'Estrategias para generar ingresos con tu juego.\n\nModelos de monetización:\n1. Premium: pago único\n2. Freemium: gratis con compras\n3. Ads: publicidad integrada\n4. Suscripciones: pago recurrente\n\nTipos de anuncios:\n- Banner: siempre visible\n- Interstitial: pantalla completa\n- Rewarded: recompensa por ver\n- Native: integrado al juego', 'Genera ingresos con tu juego móvil', 2);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Testing y Debugging', 'https://docs.unity3d.com/uploads/Main/Console.png', 'Encuentra y corrige errores en tu juego eficientemente.\n\nTipos de testing:\n- Unit Testing: funciones individuales\n- Integration Testing: sistemas completos\n- Playtesting: experiencia del jugador\n- Performance Testing: rendimiento\n\nHerramientas de Unity:\n- Console: logs y errores\n- Profiler: rendimiento\n- Frame Debugger: renderizado\n- Memory Profiler: uso de memoria', 'Encuentra y soluciona bugs rápidamente', 3);

INSERT INTO tutoriales (titulo, imagen, cuerpo, descripcion, usuario_id) VALUES 
('Publicación en Steam', 'https://partner.steamgames.com/public/images/steamworks_docs/english/steam_logo.png', 'Guía completa para publicar tu juego en Steam.\n\nPasos principales:\n1. Registro en Steamworks\n2. Pago de tarifa ($100 USD)\n3. Configuración de la página\n4. Subida de builds\n5. Revisión de Valve\n6. Lanzamiento\n\nRequisitos importantes:\n- Juego funcional completo\n- Screenshots de calidad\n- Trailer del juego\n- Descripción detallada\n- Clasificación de edad', 'Lleva tu juego a la plataforma más grande', 1);
